### ISSUE TITLE
Indigo Compilation

### ISSUE THREAD

**Issue by eokeeffe** [aharmat/mcptam#3]
Heya,thanks for the awesome package.
Works really well

Thought I might add that for compiling on ROS Indigo I had to change two things
The first in ChainBundle.cc , on line 433 , change g2o::aligned_allocator to Eigen::aligned_allocator

then in the CMakeLists.txt add -fopenmp to the set(CMAKE_CXX_FLAGS argument list

after that everything compiles

thanks again

**Comment by aharmat** [comment]
These suggestions have been added to the master branch and are in the latest release 0.1.2. Hope that does the trick for Indigo.
